### ISSUE TITLE
Better notifications behaviour

### ISSUE THREAD

**Issue by fcheslack** [fcheslack/zotero-theme#1]
Remove most of the notifications preferences since we don't want that vanilla functionality (I believe this required overriding core).

If possible, don't re-send thread updates until user visits the forum again.

Notify moderators when there are posts in the queue (if it doesn't by default).

**Comment by fcheslack** [comment]
Disabling more of the notification preferences is possible by changing the config (Garden.Profile.ShowActivities to false). Not sure if that's new, or I just hadn't found reference to it before.

Not re-sending thread updates should be handled by the BetterNotifications plugin.
"Implements vBulletin/PHPBB-style e-mail notifications for users who bookmark discussions. They will only receive one notification e-mail until they re-visit the discussion."

Notification of moderation is now visible in the UI for mods/admins when browsing, but no email notifications are sent. 
https://github.com/fcheslack/zotero-theme/commit/38a22ced344d8306b9d0dcefd383582ed052ad8e

**Comment by gracile-fr** [comment]
> If possible, don't re-send thread updates until user visits the forum again.

That's actually a pity! It was very useful to get these updates with the old version. "BetterNotifications"…

**Comment by dstillman** [comment]
@gracile-fr: This was just bringing the new site closer to the old version, which didn't send updates for any thread until you revisited the forum. There was a setting in the old site to send for every message, which you might have had enabled, but that's not what it did for most people.

**Comment by dstillman** [comment]
If you want to follow each post, you can subscribe to the RSS feed: https://forums.zotero.org/comments/feed.rss (with an optional Limit parameter depending on your refresh frequency)

**Comment by gracile-fr** [comment]
Yes, I know it was an option. Really useful to get notifications when a topic which is of interest to me is active. I had used the RSS feed but you get everything (and/but just the title). I'm sure I'm not the only one who would be very happy to have this option again :-)

**Comment by dstillman** [comment]
> and/but just the title

Not sure what you mean by that. It's a full-text feed.

**Comment by gracile-fr** [comment]
Probably because I didn't use a feed reader. I had added the feed as a a <a href="https://support.mozilla.org/t5/Basic-Browsing/Live-Bookmarks-Subscribe-to-a-web-page-for-news-and-updates/ta-p/478">live bookmark</a> directly in the Firefox's Bookmarks toolbar. Would you recommend me a feed reader or anything (yet, specific email notifications would be better ;-) ) ?

**Comment by dstillman** [comment]
Thunderbird will show full content and can also do threading of messages, which I find to be extremely useful for following the forums.

**Comment by gracile-fr** [comment]
Just tried it, interesting (and happy to see other people still using TB), thanks.
>and can also do threading of messages

How ?

**Comment by dstillman** [comment]
View -> Sort by -> Threaded

**Comment by gracile-fr** [comment]
That's what I've done, without success :-( thanks anyway
